CUDA_VISIBLE_DEVICES=0,1,2,3,4 python -m torch.distributed.launch --nproc_per_node=5 --master_port 10244 oscar/run_instance_pred_cls.py \
  --eval_model_dir pretrained_model/pretrained_base/checkpoint-2000000/ \
  --do_train \
  --train_dir /data_local/yutianyu/VinVL/scene_graph_benchmark/datasets/visualgenome/ \
  --test_dir /data_local/yutianyu/VinVL/scene_graph_benchmark/datasets/visualgenome/ \
  --do_lower_case \
  --learning_rate 5e-5 \
  --per_gpu_train_batch_size 32 \
  --per_gpu_eval_batch_size 16 \
  --freeze_embedding \
  --keep_ratio 230.02 \
  --shot 200\
  --eval_period 1 \
  --num_train_epochs 15 \
  --output_dir ../oscar_output/lr5e-5_bsz160_MLP_low_resource_200_shot_15_epoch
